image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - mkdir origin && cp -r archetypes/ assets/ layouts/ static/ theme.toml origin/
  - cd exampleSite && hugo --gc --themesDir ..
  artifacts:
    paths:
    - exampleSite/public
  only:
  - master
