image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - cd exampleSite
  - hugo --gc --themesDir ../..
  artifacts:
    paths:
    - exampleSite/public
  only:
  - master
