name = "Origin"
license = "MIT"
licenselink = "https://gitlab.com/asleeppiano/origin-hugo-theme/-/blob/master/LICENSE"
description = "simple theme for hugo"
homepage = "https://asleeppiano.gitlab.io/origin-hugo-site/"
tags = ["blog", "responsive", "light", "simple"]
features = []
min_version = "0.60"

[author]
  name = "Andrey Parfenov"
  homepage = ""
