name = "Origin"
license = "MIT"
licenselink = ""
description = "simple theme for hugo"
homepage = "http://example.com/"
tags = ["blog", "responsive", "light", "simple"]
features = []
min_version = "0.41"

[author]
  name = "Andrey Parfenov"
  homepage = ""
